# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Digest-CMAC
version:      0.02
version_from: lib/Digest/CMAC.pm
installdirs:  site
requires:
    Crypt::Rijndael:               0
    MIME::Base64:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
